# Identificación de la aplicación
spring.application.name=petstore-orders

# CONFIGURACIÓN DE BASE DE DATOS (La Wallet de Oracle Cloud)
spring.datasource.url=jdbc:oracle:thin:@midbduoc_high?TNS_ADMIN=C:/Users/Volg/Documents/BASEDEDATOSDUOC/Wallet_MIDBDUOC
spring.datasource.username=fullstack1
spring.datasource.password=SumativasFullStack2026
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIÓN DE LOGGING
# Establecer el nivel de log global
logging.level.root=INFO
# Nivel DEBUG para nuestro paquete principal
logging.level.com.example.petstore_orders=DEBUG
# Nivel INFO para el framework spring
logging.level.org.springframework=INFO
# Ver las consultas SQL generadas
logging.level.org.hibernate.SQL=DEBUG

# SEGURIDAD (Basic Auth)
spring.security.user.name=fullstack1
spring.security.user.password=SumativasFullStack2026
